apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  labels:
    app: mysql-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
